
name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [lts/*]
        
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        
        
    - name: Build API
      run: |
           cd ./api
           npm install
           npm run lint
           npm run build
    - name: Build Backend
      run: |
           cd ./backend
           npm install
           npm run lint
           npm run build
    - name: Build Frontend
      run: |
           cd ./frontend
           npm install
           npm run lint
           npm run build
    - name: Build Mobile App
      run: |
           cd ./mobile
           npm install
           npm run lint
           npm run ts:check
